Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
  config.vm.base_mac = "0800278F7A9F"

  config.vm.provisioner = :chef_solo 
  
  # Use both our server-specific cookbooks, and the common ones
  config.chef.cookbooks_path = [
    File.expand_path('../cookbooks', __FILE__), 
    File.expand_path('../../common/cookbooks', __FILE__)
  ]
  config.chef.run_list = ["recipe[dev]", "recipe[clown]"]

  config.vm.network('192.168.11.5')
  
  config.vm.forward_port("ssh", 22, 22144)
  
  config.vm.share_folder("circus-packages", '/packages', File.expand_path('../../../packages', __FILE__))
  config.vm.share_folder("circus", '/circus', File.expand_path('../../..', __FILE__))
end
