# coding:utf-8
require 'rubygems'

begin
  require 'rspec/core/rake_task'
rescue LoadError
  $stderr.puts 'Run `gem install rspec -v "~> 2.0.0"` to be able to run specs'
else
  task :clear_tmp do
    FileUtils.rm_rf(File.expand_path("../tmp", __FILE__))
  end

  desc "Run specs"
  RSpec::Core::RakeTask.new do |t|
    t.pattern = 'spec/**/*_spec.rb'
    t.rspec_opts = %w(-fs --color)
    t.ruby_opts = ['-rspec/helpers/env']
  end
  task :spec => :clear_tmp
end

task :default => :spec
