begin
  require 'rspec/core/rake_task'
rescue LoadError
  $stderr.puts 'Run `gem install rspec -v "~> 2.0.0"` to be able to run specs'
else
  desc "Run specs"
  RSpec::Core::RakeTask.new do |t|
    t.pattern = 'spec/**/*_spec.rb'
    t.rspec_opts = %w(-fs --color)
    t.ruby_opts = ['-rspec/helpers/env']
  end
end
