begin
  require 'vagrant'
rescue LoadError
  puts "The vagrant gem is required to build a node"
  puts "  Execute: sudo gem install vagrant"
  exit 1
end

require File.expand_path('../../installer/tasks/installer.tasks', __FILE__)

namespace :node do
  task :ensure_node_vm do
    # Load a Vagrant environment for deployment, and ensure that it is up
    @node_env = Vagrant::Environment.new(:cwd => File.expand_path('..', __FILE__))
    @node_env.ui = Vagrant::UI::Shell.new(@node_env, Thor::Base.shell.new)
    @node_env.load!
    @node_env.cli 'up'
    
    # Standard configuration for the installer tasks
    @deploy_target = 'ssh://vagrant@192.168.11.10'
    @ssh = @node_env.vms[:default].ssh
    @root_ssh = @ssh
    @uri = URI.parse(@deploy_target)
  end

  task :reprovision => [:ensure_node_vm] do
    @node_env.cli 'provision'
  end
  task :ensure_ssh_agent => [:ensure_node_vm] do
    sh "ssh-add #{@node_env.config.ssh.private_key_path}"
  end
  
  task :build => 'install:all'
end
namespace :install do
  task :parse_args => ['node:ensure_node_vm', 'node:ensure_ssh_agent']
end
