Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  config.vm.network('192.168.11.10')
  config.vm.forward_port("ssh", 22, 22145)
end
