source :gemcutter

gem "thor", ">= 0.13.4"
gem "rest-client", ">= 1.5.0"
#gem "json", ">= 1.4.2"
gem "xmpp4r", ">= 0.5"
gem "blather", "0.4.8"
gem "uuid", "2.3.1"
gem "net-ssh", "2.0.22"
gem "net-scp", "1.0.2"

group :test do
  gem "rspec", ">= 0"
end
