# coding:utf-8
$:.unshift File.expand_path("../lib", __FILE__)

require 'rubygems'
require 'rubygems/specification'

def gemspec
  @gemspec ||= begin
    file = File.expand_path('../circus-deployment.gemspec', __FILE__)
    eval(File.read(file), binding, file)
  end
end

begin
  gem 'rspec', '~> 2.0.0'
  require 'rspec/core/rake_task'
rescue LoadError
  $stderr.puts 'Run `gem install rspec -v "~> 2.0.0"` to be able to run specs'
else
  task :clear_tmp do
    FileUtils.rm_rf(File.expand_path("../tmp", __FILE__))
  end

  desc "Run specs"
  RSpec::Core::RakeTask.new do |t|
    t.pattern = 'spec/**/*_spec.rb'
    t.rspec_opts = %w(-fs --color)
  end
  task :spec => :clear_tmp
end

begin
  require 'rake/gempackagetask'
rescue LoadError
  task(:gem) { $stderr.puts '`gem install rake` to package gems' }
else
  Rake::GemPackageTask.new(gemspec) do |pkg|
    pkg.gem_spec = gemspec
  end
  task :gem => :gemspec
end

desc "install the gem locally"
task :install => :package do
  sh %{gem install pkg/#{gemspec.name}-#{gemspec.version}}
end

desc "validate the gemspec"
task :gemspec do
  gemspec.validate
end

task :package => :gemspec
task :default => :spec
